basic.pause(1000)
MakeyMakey.sx1509_init()
MakeyMakey.typeKey(Key.W)
MakeyMakey.typeKey(Key.A)
MakeyMakey.typeKey(Key.S)
MakeyMakey.typeKey(Key.D)
MakeyMakey.typeKey(Key.F)
MakeyMakey.typeKey(Key.G)
MakeyMakey.clickMouse(MouseButtons.RIGHT)
MakeyMakey.moveMouseForSeconds(MouseDirections.LEFT, 500)
MakeyMakey.clickMouse(MouseButtons.LEFT)
MakeyMakey.moveMouseForSeconds(MouseDirections.RIGHT, 500)
MakeyMakey.moveMouseForSeconds(MouseDirections.UP, 500)
MakeyMakey.moveMouseForSeconds(MouseDirections.DOWN, 500)
